#!/bin/bash

# install.sh
#
# This is just a little script to:
# - create home for pathr
# - install microk8s
# - install bunch of tools, plugins, etc

set -ue

USERNAME="pathr"

SNAP_CHANNEL_VERSION="1.28"
_divider="--------------------------------------------------------------------------------"
_prompt=">>>"
_indent="   "

header() {
    cat 1>&2 <<EOF
                      _____      _   _          
                     |  __ \    | | | |         
                     | |__) |_ _| |_| |__  _ __ 
                     |  ___/ _' | __| '_ \| '__|
                     | |  | (_| | |_| | | | |   
                     |_|   \__,_|\__|_| |_|_|   
                            
                            
                    P A T H R
                    Installer


$_divider
Website: https://pathr.ai
$_divider

EOF
}

usage() {
    cat 1>&2 <<EOF
pathr-install
The installer for Pathr (https://pathr.ai)

USAGE:
    pathr-install [FLAGS] [OPTIONS]

FLAGS:
    -y                      Disable confirmation prompt.
    -h, --help              Prints help information
EOF
}

main() {

    header

    local prompt=yes
    # Parse command-line options
    while getopts "hyu:" opt; do
        case ${opt} in
            h)
                usage
                exit 0
                ;;
            y)
                prompt=no
                ;;
            u)
                USERNAME=$OPTARG
                ;;
            \? )
                echo "Invalid option: $OPTARG" 1>&2
                show_usage
                exit 1
                ;;
            :)
                echo "Invalid option: $OPTARG requires an argument" 1>&2
                show_usage
                exit 1
                ;;
        esac
    done


    if [ "$prompt" = "yes" ]; then
        echo "$_prompt Ready to proceed? (y/n)"
        echo ""

        while true; do
            read -rp "$_prompt " _choice </dev/tty
            case $_choice in
                n)
                    err "exiting"
                    ;;
                y)
                    break
                    ;;
                *)
                    echo "Please enter y or n."
                    ;;
            esac
        done

        echo ""
        echo "$_divider"
        echo ""
    fi

    verify

    install
}

user_can_sudo() {
  # Check if sudo is installed
  need_cmd sudo

  # The following command has 3 parts:
  #
  # 1. Run `sudo` with `-v`. Does the following:
  #    • with privilege: asks for a password immediately.
  #    • without privilege: exits with error code 1 and prints the message:
  #      Sorry, user <username> may not run sudo on <hostname>
  #
  # 2. Pass `-n` to `sudo` to tell it to not ask for a password. If the
  #    password is not required, the command will finish with exit code 0.
  #    If one is required, sudo will exit with error code 1 and print the
  #    message:
  #    sudo: a password is required
  #
  # 3. Check for the words "may not run sudo" in the output to really tell
  #    whether the user has privileges or not. For that we have to make sure
  #    to run `sudo` in the default locale (with `LANG=`) so that the message
  #    stays consistent regardless of the user's locale.
  #
  ! LANG= sudo -n -v 2>&1 | grep -q "may not run sudo"
}

verify() {
  if ! user_can_sudo; then
    err "need sudo"
  fi
}

setup() {
    say 'runnig setup'
    setup_zsh
    setup_microk8s
}

install() {
    say "installation start"
    install_microk8s
    install_kubectl
    install_k9s
    install_helm
    install_zsh
    install_other
    install_flux
    say "installation end"
}

install_other() {
    say "installing other tools"
    sudo apt update && sudo apt install -y fzf dos2unix speedtest-cli tree apt-offline jq wget ffmpeg apt-transport-https ca-certificates curl gnupg-agent software-properties-common zip unzip python3-pip mlocate
}

install_flux() {
    say "installation flux"
    curl -s https://fluxcd.io/install.sh | sudo bash
}

install_zsh() {
    say "installing zsh"
    need_cmd apt
    sudo apt install -y zsh
    zsh --version
}

install_helm() {
    say "installing helm"
    sudo snap install helm --classic
}

install_k9s() {
    say "installing k9s"
    need_cmd snap
    sudo snap install k9s --devmode
}

install_kubectl() {
    say "installing kubectl"
    need_cmd snap
    sudo snap install kubectl --classic
}

install_microk8s() {
    say "installing microk8s"
    need_cmd snap
    sudo snap install microk8s --classic --channel=${SNAP_CHANNEL_VERSION}

    # wait untill ready
    sudo microk8s status --wait-ready

    # enabled addons
    sudo microk8s enable dns
    sudo microk8s enable hostpath-storage

    # add user to microk8s group
    sudo usermod -a -G microk8s ${USERNAME}
}

say() {
    printf 'pathr-install: %s\n' "$1"
}

err() {
    say "$1" >&2
    exit 1
}

need_cmd() {
    if ! check_cmd "$1"; then
        err "need '$1' (command not found)"
    fi
}

check_cmd() {
    command -v "$1" > /dev/null 2>&1
}

main "$@" || exit 1